version: '3'
services:
  mysql_db:
    image: 'mysql:8.0'
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ShoppingApp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - common-network

  backend_service:
    image: shopping-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '8081:8081'
    environment:
      DB_HOST: mysql_db
    depends_on:
      - mysql_db
    networks:
      - common-network

networks:
  common-network:
    driver: bridge

volumes:
  db_data:
    driver: local


#version: "3.7"
#services:
#  mysql_db:
#    image: "mysql:8.0"
#    ports:
#      - "3307:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: ShoppingApp
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#    networks:
#      - common-network
#
#  api_service:
#    image: shopping-app
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#    ports:
#      - "8080:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3307/ShoppingApp?useSSL=false&createDatabaseIfNotExist=true
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#    depends_on:
#      - mysql_db
#    links:
#      - mysql_db:mysql_db
#    networks:
#      - common-network
#
#networks:
#  common-network:
#    driver: bridge
#
#volumes:
#  db_data:
#    driver: local
