INSERT INTO product (product_name, price, description, available_quantity)
VALUES ('IPhone mini', 60000.00,'The iPhone is a smartphone made by Apple that combines a computer.',100),
       ('Soup - Campbells Chicken', 24532.11, 'Dilation of Abdominal Aorta with 3 Drug-elut, Perc Approach', 26),
       ('Oranges', 54713.59, 'Release Pericardium, Percutaneous Approach', 18),
       ('Cookie Dough - Peanut Butter', 38952.21, 'Bypass R Com Iliac Art to L Femor A w Autol Art, Open', 7),
       ('Coconut - Shredded, Unsweet', 51829.75, 'Removal of Synth Sub from L Extraoc Muscle, Perc Approach', 37),
       ('Pail - 4l White, With Handle', 63165.98, 'Change Other Device in Upper Tendon, External Approach', 54),
       ('Apple - Royal Gala', 79828.74, 'Alteration of L Ext Ear with Autol Sub, Open Approach', 59),
       ('Mushroom - Chanterelle, Dry', 22655.75, 'Drainage of Right Metatarsal, Open Approach', 34),
       ('Soup - Cream Of Potato / Leek', 71805.86, 'Transfer Oculomotor Nrv to Accessory Nrv, Perc Endo Approach', 55),
       ('Pasta - Angel Hair', 53200.01, 'Dilate R Com Iliac Art, Bifurc, w 4 Drug-elut, Perc Endo', 53),
       ('Thermometer Digital', 47108.46, 'Replacement of Pulmonary Valve with Autol Sub, Perc Approach', 34),
       ('Steam Pan Full Lid', 86750.15, 'Bypass Sup Vena Cava to Pulm Trunk w Synth Sub, Open', 100),
       ('Bread - Calabrese Baguette', 8235.57, 'Fluoroscopy of Inferior Vena Cava', 24),
       ('Veal Inside - Provimi', 5207.45, 'Supplement R Pulm Vein with Nonaut Sub, Open Approach', 56),
       ('Cookies Oatmeal Raisin', 53568.46, 'Destruction of Femoral Nerve, Percutaneous Approach', 73),
       ('Bread - Assorted Rolls', 96748.07, 'Occlusion L Renal Vein w Intralum Dev, Perc Endo', 39),
       ('Coffee - Dark Roast', 3447.16, 'Bypass L Int Jugular Vein to Up Vein w Autol Vn, Perc Endo', 74),
       ('Pumpkin - Seed', 61916.55, 'Supplement Right Lacrimal Duct with Synth Sub, Via Opening', 43),
       ('Sauce - Hp', 66817.88, 'Fusion of 2-7 T Jt, Ant Appr A Col, Perc Approach', 27),
       ('Tomatoes - Yellow Hot House', 5018.61, 'Supplement L Seminal Vesicle w Nonaut Sub, Perc Endo', 85),
       ('Beer - Rickards Red', 58973.09, 'Insertion of Infusion Dev into R Pleural Cav, Open Approach', 89),
       ('Pastry - Banana Tea Loaf', 74107.32, 'Manual Therapy Techniques Treatment of Integu Body', 84),
       ('Soup - Campbells, Minestrone', 3765.77, 'Drainage of Bone Marrow, Percutaneous Endoscopic Approach', 85),
       ('Beef Wellington', 28309.09, 'Reattachment of Cul-de-sac, Open Approach', 62),
       ('Pie Box - Cello Window 2.5', 74450.88, 'Plain Radiography of R Brachioceph A using Oth Contrast', 82),
       ('Wine - Red, Antinori Santa', 77559.01, 'Insertion of Ext Fix into R Wrist Jt, Perc Endo Approach', 61),
       ('Lychee - Canned', 59128.35, 'Excision of R Int Mamm Art, Perc Endo Approach', 56),
       ('Veal - Osso Bucco', 24903.75, 'Resection of Prepuce, Percutaneous Endoscopic Approach', 44),
       ('Eggs - Extra Large', 972.06, 'Excision of Right Inguinal Region, Perc Endo Approach', 29),
       ('Wine - Chateau Aqueria Tavel', 30447.24, 'Reposition Occip Jt with Int Fix, Perc Approach', 19),
       ('Salmon - Canned', 57740.82, 'Release Left Breast, Endo', 43),
       ('Cumin - Ground', 56185.06, 'Drainage of Cerebral Hemisphere, Open Approach', 27),
       ('Clams - Bay', 18179.18, 'Supplement Dura Mater with Autol Sub, Perc Approach', 95),
       ('Beef - Sushi Flat Iron Steak', 9582.71, 'Dilate L Subclav Art, Bifurc, w Intralum Dev, Perc Endo', 94),
       ('Icecream - Dstk Cml And Fdg', 29509.28, 'Extirpate matter from L Low Arm & Wrist Tendon, Perc Endo', 75),
       ('Cake - Mini Cheesecake', 73292.7, 'Reposition Right Patella with Int Fix, Perc Approach', 17),
       ('Shrimp - 16/20, Peeled Deviened', 33048.13, 'Drainage of Left Mastoid Sinus, Perc Endo Approach, Diagn', 10),
       ('Soup - Knorr, French Onion', 19859.26, 'Fusion of Thor Jt, Post Appr P Col, Perc Endo Approach', 18),
       ('Bread - Granary Small Pull', 48026.29, 'Dilation of Left Upper Lobe Bronchus, Perc Endo Approach', 35),
       ('Silicone Parch. 16.3x24.3', 48982.8, 'Drain R Low Leg Subcu/Fascia w Drain Dev, Open', 30),
       ('Pepper - Black, Crushed', 3122.99, 'Revision of Synth Sub in Hepatobil Duct, Perc Endo Approach', 19),
       ('Wine - Ice Wine', 37605.39, 'Reattachment of Stomach, Percutaneous Endoscopic Approach', 71),
       ('Cheese - Goat', 79961.03, 'Coord/Dexterity Trmt Musculosk Head, Neck w Assist Equip', 70),
       ('Wine - White, Lindemans Bin 95', 48246.33, 'Dilate L Int Mamm Art, Bifurc, w 4+ Intralum Dev, Perc Endo', 11),
       ('Veal - Brisket, Provimi, Bone - In', 62752.38, 'Reposition L Femur Shaft with Monopln Ext Fix, Open Approach', 51),
       ('Wine - Riesling Dr. Pauly', 62204.03, 'Drainage of L Shoulder Bursa/Lig, Perc Endo Approach, Diagn', 68),
       ('Brandy - Bar', 18532.41, 'Fluoroscopy R Int Carotid w Oth Contrast, Laser Intraop', 55),
       ('Sambuca - Ramazzotti', 16064.46, 'Plain Radiography of Thoraco-Abdominal Aorta', 88),
       ('Crab - Claws, Snow 16 - 24', 71779.88, 'Introduction of Anti-inflammatory into Bones, Perc Approach', 8),
       ('Beer - Sleemans Honey Brown', 93732.42, 'Revise Synth Sub in Head & Neck Subcu/Fascia, Perc', 97),
       ('Tamarillo', 4563.75, 'Reposition Left Palatine Bone with Int Fix, Open Approach', 52),
       ('Table Cloth 90x90 White', 13047.96, 'Dilation of Thoracic Aorta, Descending, Perc Approach', 57),
       ('Ocean Spray - Ruby Red', 80938.31, 'Removal of Other Device from Mediastinum, Perc Endo Approach', 2),
       ('Remy Red', 33510.75, 'Introduction of Local Anesthetic into Low GI, Perc Approach', 96),
       ('Glass - Wine, Plastic, Clear 5 Oz', 52950.96, 'Exercise Treatment of Circ Body using Aerobic Equipment', 41),
       ('Pie Filling - Apple', 48148.24, 'Bypass Abd Aorta to B Ext Ilia w Synth Sub, Perc Endo', 45),
       ('Ice Cream Bar - Oreo Cone', 14191.82, 'Destruction of Glossopharyngeal Nerve, Open Approach', 35),
       ('Wine - German Riesling', 75006.84, 'Bypass L Ext Iliac Art to R Int Ilia, Perc Endo Approach', 90),
       ('Corn Shoots', 415.83, 'Supplement Upper Esophagus with Autol Sub, Endo', 18),
       ('Wine - Spumante Bambino White', 90221.92, 'Bypass Right Femoral Artery to Low Ex Vein, Open Approach', 54),
       ('Nantucket - Pomegranate Pear', 76496.57, 'Insert Card Rhythm Dev in Abd Subcu/Fascia, Perc', 46),
       ('Tea - Honey Green Tea', 19311.95, 'Revision of Ext Fix in R Pelvic Bone, Extern Approach', 81),
       ('Wine - Sauvignon Blanc', 88013.46, 'Excision of Right Upper Arm Skin, External Approach, Diagn', 74),
       ('Urban Zen Drinks', 5552.74, 'Drainage of Right Finger Phalanx, Open Approach', 60),
       ('Pickle - Dill', 91417.72, 'Extirpation of Matter from R Face Vein, Perc Endo Approach', 48),
       ('Veal - Heart', 76115.76, 'Supplement L Innom Vein with Nonaut Sub, Perc Approach', 48),
       ('Soup - Knorr, Ministrone', 70590.26, 'Division of Left Lower Femur, Open Approach', 65),
       ('Garbag Bags - Black', 70204.71, 'Dilate L Colic Art, Bifurc, w 4+ Intralum Dev, Perc', 26),
       ('Wine - Zonnebloem Pinotage', 13913.73, 'Excision of Right Ankle Region, Perc Endo Approach', 13),
       ('Vermacelli - Sprinkles, Assorted', 28284.25, 'Division of Lumbosacral Plexus, Open Approach', 84),
       ('Ginger - Fresh', 77697.58, 'Supplement L Thorax Muscle w Nonaut Sub, Perc Endo', 90),
       ('Salami - Genova', 81122.32, 'Transfer Right Thorax Muscle with Subcu, Perc Endo Approach', 89),
       ('Nectarines', 68020.64, 'Supplement Left Thorax Tendon with Nonaut Sub, Open Approach', 35),
       ('Lobster - Baby, Boiled', 57158.48, 'Excision of Chordae Tendineae, Perc Endo Approach', 57),
       ('Oranges', 12682.63, 'Occlusion L Int Jugular Vein w Intralum Dev, Open', 73),
       ('Aspic - Light', 90266.95, 'ROM & Jt Mobility Treatment of Neuro Up Back/UE', 61),
       ('Gingerale - Diet - Schweppes', 85756.61, 'Extirpation of Matter from L Com Carotid, Open Approach', 49),
       ('Sprouts Dikon', 69695.61, 'Supplement R Up Leg Subcu/Fascia w Nonaut Sub, Open', 64),
       ('Lettuce - California Mix', 68498.91, 'Low Dose Rate (LDR) Brachytherapy of Tongue using Cesium 137', 15),
       ('Coffee - Hazelnut Cream', 27686.05, 'LDR Brachytherapy of Jejunum using Oth Isotope', 9),
       ('Basil - Thai', 84784.85, 'Insert of Infusion Dev into R Colic Art, Perc Endo Approach', 42),
       ('Beer - Blue Light', 81261.74, 'Occlusion of Small Intestine, Percutaneous Approach', 39),
       ('Veal - Heart', 86307.39, 'Bypass L Int Carotid to L Extracran Art w Synth Sub, Open', 32),
       ('Fish - Bones', 45004.89, 'Removal of Radioactive Element from Face, Perc Endo Approach', 10),
       ('Pop Shoppe Cream Soda', 94631.26, 'Excision of Right Kidney Pelvis, Via Opening, Diagn', 37),
       ('Pasta - Rotini, Colour, Dry', 5732.86, 'Drain of R Up Lung Lobe with Drain Dev, Perc Endo Approach', 75),
       ('Black Currants', 67323.8, 'Resection of Right Epididymis, Open Approach', 62),
       ('Coffee - Dark Roast', 51044.18, 'Release Face Artery, Percutaneous Approach', 9),
       ('Truffle - Peelings', 83720.22, 'Drainage of Right Humeral Shaft, Open Approach, Diagnostic', 86),
       ('Walkers Special Old Whiskey', 53316.0, 'Reattachment of Cervix, Open Approach', 11),
       ('Sausage - Andouille', 29459.0, 'Removal of Int Fix from L Sternoclav Jt, Perc Endo Approach', 66),
       ('Pie Filling - Cherry', 73834.08, 'Extirpation of Matter from Right Mandible, Perc Approach', 10),
       ('Wine - Manischewitz Concord', 96247.51, 'Revision of Spacer in Left Carpal Joint, External Approach', 32),
       ('Smoked Paprika', 90867.89, 'Removal of Infusion Device from Heart, Perc Endo Approach', 21),
       ('Bread - Hamburger Buns', 13946.17, 'Insertion of Infusion Device into Abd Wall, Perc Approach', 7),
       ('Bread - Roll, Whole Wheat', 33381.77, 'Supplement Left Elbow Region with Autol Sub, Open Approach', 72),
       ('Soup - Campbells, Butternut', 422.24, 'Extraction of Left Maxillary Sinus, Perc Endo Approach', 3),
       ('Juice - Pineapple, 341 Ml', 17607.41, 'Reposition Right Renal Artery, Percutaneous Approach', 56);
